version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nextjs:
        patterns:
          - "next"
          - "react*"
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      testing:
        patterns:
          - "jest*"
          - "@types/jest*"
      dev-dependencies:
        patterns:
          - "eslint*"
          - "prettier*"
          - "typescript"
          - "turbo"

  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/cms"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/editor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"
